{\rtf1\ansi\ansicpg1251\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 .AppleSystemUIFontMonospaced-Regular;}
{\colortbl;\red255\green255\blue255;\red35\green38\blue42;\red244\green244\blue244;}
{\*\expandedcolortbl;;\cssrgb\c18431\c20000\c21569;\cssrgb\c96471\c96471\c96471;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26 \cf2 \cb3 \expnd0\expndtw0\kerning0
CC = cc\
CFLAGS = -std=c99 -pedantic -Wall\
OBJECTS = main.cpp\
\
all: main.cpp\
\
filename.o: main.cpp\
    $(CC) $(CFLAGS) -c main.cpp\
\
main.cpp: $(OBJECTS)\
    $(CC) $(OBJECTS) -o main.cpp\
\
clean:\
    rm -f *.o main.cpp}